version: "3"
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - redis
  frontend:
    build:
      context: ./frontend
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/usr/src/app
    stdin_open: true
    tty: true
    depends_on:
      - backend
  scheduler:
    build: ./scheduler
    ports:
      - "3002:3000"
    depends_on:
      - redis
  executor:
    build: ./executor
    ports:
      - "3003:3000"
    depends_on:
      - redis
  redis:
    image: redis:6.0
    ports:
      - "6379:6379"
