apiVersion: apps/v1
kind: Deployment
metadata:
  name: executor-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: executor
  template:
    metadata:
      labels:
        app: executor
    spec:
      containers:
      - name: executor
        image: scheduler-executor
        env:
        - name: REDIS_URL
          value: "redis://redis-service:6379"
